steps:
# Build the container
- name: 'gcr.io/cloud-builders/docker'
  dir: 'src/frontend/'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/github.com/sintogendeng/bank-of-anthos:${SHORT_SHA}", "-f", "Dockerfile", "."]
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'src/frontend/'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/sintogendeng/bank-of-anthos:${SHORT_SHA}']
# Adjust the manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     gcloud config unset api_endpoint_overrides/container &&
     sed -i "s/APP_VERSION_COMMIT/${COMMIT_SHA}/g" dev-kubernetes-manifests/frontend.yaml
# Create release in Google Cloud Deploy
- name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  - run
  - --filename=dev-kubernetes-manifests/frontend.yaml
  - --image=gcr.io/$PROJECT_ID/github.com/sintogendeng/bank-of-anthos:${SHORT_SHA}
  - --location=asia-southeast1-a
  - --cluster=gke-anthos